### ISSUE TITLE
Building kb file sequence

### ISSUE THREAD

**Issue by SHtress** [ostis-ai/sc-machine#135]
**Describe the bug**
Builder can't build kb, probably because of file sequence.  

**Expected behavior**
Building kb in same way of every machine without errors.

**Screenshots**
![Screenshot from 2022-08-22 16-29-31](https://user-images.githubusercontent.com/44646393/186129219-e6f95a26-eab1-4101-b234-dd2fbafa4be2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 0.7.0

**Comment by Malina09** [comment]
As in the screenshot, the name that is already used in ims is duplicated in our pc database, there is a type conflict, since our concept of _name is link. If you change the name, the conflict in the database is resolved. Therefore, I suggest replacing the concept of _name in the pc database with _name_link. By the same principle, in order to avoid such a problem in the future, I also suggest replacing _surname with _surname_link and _honorific with _honorific_link. You need to change the following files: patient---care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/i_am_sorry_to_hear_that.scs

**Comment by Malina09** [comment]
As in the screenshot, the name that is already used in ims is duplicated in our pc database, there is a type conflict, since our concept of _name is link. If you change the name, the conflict in the database is resolved. Therefore, I suggest replacing the concept of _name in the pc database with _name_link. By the same principle, in order to avoid such a problem in the future, I also suggest replacing _surname with _surname_link and _honorific with _honorific_link. You need to change the following files:

/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/i_am_sorry_to_hear_that.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/i_am_sorry.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/pity.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/i_am_grateful_to_youfor_this.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/thank_you.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/thanks.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_pleasure/i_am_glad_for_you.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_pleasure/that_is_great.scs
/patient-care/kb/old/phrases/concept_declarative_phrase/concept_phrases_of_pleasure/good_for_you_phrase.gwf
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_information_request_for_reasons_phrase/how_did_this_happen.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_information_request_for_reasons_phrase/tell_me_about_your_reasons_for_it.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/is_there_anything_you_can_tell_me_about_this_place.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/tell_me_more_about_this_place.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/tell_me_something_about_this_place.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/what_will_you_do_there.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/why_are_you_going_there.scs
/patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_plans/what_are_your_plans_for_today_phrase.gwf
-/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_calming_phrase/concept_calming_phrase.gwf
patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_negative_dialog_end_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_neutral_dialog_end_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_positive_dialog_end_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_negative_interruption_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_neutral_interruption_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_positive_interruption_responce_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_negative_greeting_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_neutral_greeting_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_positive_greeting_reply_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_phrase_about_the_variability_of_weather.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_question_about_plans_phrase.gwf
/patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_question_about_preferred_time_of_year_phrase.gwf

In all scs files, you need to change
@var_name
=>nrel_system_identifier:
[_name_link];;
concept_phrase_of_compassion ->
[I'm sorry to hear that, ${_name_link}.]

**Comment by Malina09** [comment]
As in the screenshot, the name that is already used in ims is duplicated in our pc database, there is a type conflict, since our concept of _name is link. If you change the name, the conflict in the database is resolved. Therefore, I suggest replacing the concept of _name in the pc database with _name_link. By the same principle, in order to avoid such a problem in the future, I also suggest replacing _surname with _surname_link and _honorific with _honorific_link. You need to change the following files:

- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/i_am_sorry_to_hear_that.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/i_am_sorry.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_compassion/pity.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/i_am_grateful_to_youfor_this.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/thank_you.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_gratitude/thanks.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_pleasure/i_am_glad_for_you.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_neutral_phrase/concept_politeness_phrase/concept_phrase_of_pleasure/that_is_great.scs
- /patient-care/kb/old/phrases/concept_declarative_phrase/concept_phrases_of_pleasure/good_for_you_phrase.gwf
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_information_request_for_reasons_phrase/how_did_this_happen.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_information_request_for_reasons_phrase/tell_me_about_your_reasons_for_it.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/is_there_anything_you_can_tell_me_about_this_place.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/tell_me_more_about_this_place.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/tell_me_something_about_this_place.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/what_will_you_do_there.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_location/why_are_you_going_there.scs
- /patient-care/kb/old/phrases/concept_interrogative_phrase/concept_interrogative_phrase_about_plans/what_are_your_plans_for_today_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_calming_phrase/concept_calming_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_negative_dialog_end_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_neutral_dialog_end_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_dialog_end_phrase/concept_positive_dialog_end_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_negative_interruption_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_neutral_interruption_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_finish_dialog_phrase/concept_interruption_phrase/concept_positive_interruption_responce_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_negative_greeting_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_neutral_greeting_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_greeting_phrase/concept_positive_greeting_reply_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_phrase_about_the_variability_of_weather.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_question_about_plans_phrase.gwf
- /patient-care/kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_weather_phrase/common_weather_message_responce_phrase/concept_question_about_preferred_time_of_year_phrase.gwf

In all scs files, you need to change:
**@var_name**
=>nrel_system_identifier:
[**_name_link**];;
concept_phrase_of_compassion ->
[I'm sorry to hear that, ${**_name_link**}.]
