### ISSUE TITLE
Leaks and uninitialized memory usage

### ISSUE THREAD

**Issue by VasKho** [ostis-ai/sc-machine#24]
**Bug**
During moving sanitizers I've found that there are a lot of memory leaks and uninitialized memory usage. Cause of nonzero return code it breaks build process.

**To Reproduce**
```shell
cd sc-machine/
cmake -B build -DSC_USE_SANITIZER=address
make -C build
```

```shell
cd sc-machine/
cmake -B build -DSC_USE_SANITIZER=memory
make -C build
```

**Expected behavior**
Build without errors.

**Desktop**
 - OS: Ubuntu 20.04
 - Version 0.6.0

**Additional context**
You may find tested code [here](https://github.com/VasKho/sc-machine/tree/sanitizer)
It's possible to ignore errors using *-i* and *-k* options of `make`, but it'd be perfect to 
eliminate this problems.

**Comment by FallenChromium** [comment]
From my testings, the results are inconclusive for now:
1. -DSC_USE_SANITIZER=address, compiler: Clang13, platform: Darwin_arm64 (macOS) - no warnings, build finishes succesfully.
2. -DSC_USE_SANITIZER=memory - not supported on my platform (darwin_arm64) - could be tested inside Linux VM, I'm working on it

**Comment by FallenChromium** [comment]
Another test: 
1. Ubuntu 20.04 ARM64,  compiler is GCC9.4, `-DSC_USE_SANITIZER=address` - tons of inderect leaks, build fails. 
```
Indirect leak of 39 byte(s) in 1 object(s) allocated from:
    #0 0xffff879630c8 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0xffff862de27c  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x6c627c)
    #2 0xffff862ddfd8  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x6c5fd8)
    #3 0xffff86498a58  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x880a58)
    #4 0xffff86499050  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x881050)
    #5 0xffff8649a5a4  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x8825a4)
    #6 0xffff864c8718  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x8b0718)
    #7 0xffff864d01d4  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x8b81d4)
    #8 0xffff864cda74  (/usr/lib/llvm-10/lib/libclang-10.so.1+0x8b5a74)
```
Interestingly, in indirect leaks traceback, you can see that the ASAN is from clang10. This is a problem, because as stated on the [AddressSanitizer page](https://github.com/google/sanitizers/wiki/AddressSanitizer), 

"Q: Can I mix code instrumented by Clang with code instrumented by GCC? Or can I at least compile code with Clang and link against GCC ASan runtime and vice versa?
A: No, you cannot, Clang and GCC have completely incompatible ASan implementations, you cannot mix them in any way. "

2. Ubuntu 20.04 ARM64, Clang10 compiler, `-DSC_USE_SANITIZER=address` - build finishes successfully
3. Ubuntu 20.04 ARM64, Clang10 compiler, `-DSC_USE_SANITIZER=memory` - build error:
```Uninitialized bytes in __interceptor_memchr at offset 0 inside [0xffff9d803910, 8)
==12398==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0xffffa3514c3c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const (/lib/aarch64-linux-gnu/libstdc++.so.6+0x13ac3c)
    #1 0xffffa35fc214 in boost::program_options::detail::cmdline::parse_long_option(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) (/lib/aarch64-linux-gnu/libboost_program_options.so.1.71.0+0x2b214)
    #2 0xffffa35fc818  (/lib/aarch64-linux-gnu/libboost_program_options.so.1.71.0+0x2b818)
    #3 0xffffa35fa548 in boost::program_options::detail::cmdline::run() (/lib/aarch64-linux-gnu/libboost_program_options.so.1.71.0+0x29548)
    #4 0xaaaae3c61274 in boost::program_options::basic_command_line_parser<char>::run() (/home/fallen/sc-machine/bin/sc-code-generator+0x14d274)
    #5 0xaaaae3c30748 in boost::program_options::basic_parsed_options<char> boost::program_options::parse_command_line<char>(int, char const* const*, boost::program_options::options_description const&, int, boost::function1<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>) (/home/fallen/sc-machine/bin/sc-code-generator+0x11c748)
    #6 0xaaaae3c2db4c in main (/home/fallen/sc-machine/bin/sc-code-generator+0x119b4c)
    #7 0xffffa315bd4c in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x20d4c)
    #8 0xaaaae3b565f8 in _start (/home/fallen/sc-machine/bin/sc-code-generator+0x425f8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/lib/aarch64-linux-gnu/libstdc++.so.6+0x13ac3c) in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const
Exiting
```
Again, the results are inconclusive and more testing is needed, but from current results I can draw a hypothesis that using AddressSanitizer with GCC is unreliable, not possible or not advisable because of the incompatibility with llvm tooling and vice versa (and AFAIK we use libllvm to generate code). We have to understand what's the underlying problem, but the solution is clearly to use `clang` as the only supported compiler when sanitizers are in use.

Can anyone check the reason behind `fsanitize=memory` error, please?
