### ISSUE TITLE
Bug with  usage of utilities with role relations 

### ISSUE THREAD

**Issue by KsenBantsevich** [ostis-ai/sc-machine#37]
**Describe the bug**
_IteratorUtils::getIterator5_ and _IteratorUtils::getAnyByOutRelation_ don't work correctly with role relations.

I tried to get a role-related object from this structure:
![image](https://user-images.githubusercontent.com/44980734/162138363-6ed7fea4-d96a-4501-b702-234e21129162.png)

With role relations, except rrel_1, utilities return an empty address. But it works correctly if I use iterators in this case. 

**To Reproduce**
1. Try to get a message from rrel_last relation in the structure above.
2. See error of empty address

**Expected behavior**
Correct work of utilities with role relations.

**Desktop:**
 - OS:  Ubuntu 20.04

**Comment by NikitaZotov** [comment]
A problem with any element getting by out relation occurs, when this relation doesn't specify. I understand it after writing this test:
![image](https://user-images.githubusercontent.com/56268020/170215928-10a2a7b5-eb8c-4d5e-bef2-6ab39265cf45.png)
Test failed, because a method `getAnyByOutRelation` doesn't understand a type of relation, when it isn't specified with some type:
![image](https://user-images.githubusercontent.com/56268020/170216426-180fe1c9-b618-48ba-a7ae-e5d48cfd4a0b.png)

I suggest specifying in the getAnyByOutRelation method the type of relation by which to search or make it so that if it did not find it in one case, it would search in another case. Are there another ideas?

**Comment by NikitaZotov** [comment]
Solved in PR #55.
